function studioControls(){return `<div class="studio-toolbar"><div class="studio-segment" role="group" aria-label="Forecast target"><button type="button" data-horizon="30" class="${modelState.horizon===30?'active':''}">+30 min</button><button type="button" data-horizon="60" class="${modelState.horizon===60?'active':''}">+60 min</button></div><span class="studio-target">${icon('calendar',19)}${modelState.data?`Target ${escapeHtml(modelTime(selectedPrediction().targetAt,true))}`:'Two model targets'}</span></div>`}
function tile(glyph,tone='green'){return `<span class="dash-tile is-${tone}">${icon(glyph,20)}</span>`}
function n(value){return modelNumber(value)}
function pct(value){return value===null?'—':`${n(value*100)}%`}
function studioHeader(title,subtitle,actions=''){const art={Forecast:'forecast',Charging:'charging',Impact:'impact',Settings:'settings'}[title]||'overview';return `<header class="dash-header studio-header"><div class="dashboard-header-art is-${art}" aria-hidden="true"></div><div class="dash-title"><p>Renewable energy planner / Ireland</p><h1>${title}</h1><span>${subtitle}</span></div>${actions}</header>`}
// The shared forecast is a GridToEv V1 historical dataset prediction (latest target in the
// dataset), never a live forecast, so every page that shows it says so in its header.
// Recovery figures are upper bounds, not what EV charging would actually absorb (review P1.8).
const RECOVERY_CAVEAT='Recovery figures are upper bounds: they assume flexible load is connected where and when the dispatch-down happens; location, local grid constraints, fleet connection, charging power and response time can all reduce them';
function dataBadge(){
  const d=modelState.data;if(!d)return '';
  const pinned=modelState.target?escapeHtml(modelTime(modelState.target,true)):null;
  const controls=`<label class="data-selection">New target from <select id="target-selection" ${modelState.loading?'disabled':''}><option value="predicted" ${modelState.selectionMode==='predicted'?'selected':''}>predicted ≥ 10 MWh, mixed risk</option><option value="unfiltered" ${modelState.selectionMode==='unfiltered'?'selected':''}>unfiltered random</option></select></label><button type="button" class="data-new-target" data-new-target ${modelState.loading?'disabled':''}>↻ New target</button>`;
  // Offline example: unrelated simulated data, visually separate from the pinned half-hour.
  if(isDemoData())return `<em class="data-badge is-demo" role="status">Offline example (simulated) · model unavailable${pinned?` · not the pinned half-hour ${pinned}`:''} · retrying</em>`;
  if(d.stale)return `<em class="data-badge is-stale" role="status">Model unreachable · last real forecast for ${pinned||escapeHtml(modelTime(d.predictions[0].targetAt,true))} (fetched ${escapeHtml(modelTime(d.stale.since))})</em>`;
  const chip=selectionChip(d.selection);
  return `<em class="data-badge">Historical dataset prediction · target ${escapeHtml(modelTime(d.predictions[0].targetAt,true))} · not a live forecast</em>${chip?`<em class="data-chip is-${chip.tone}" title="${escapeHtml(d.selection.note||'')}">${escapeHtml(chip.text)}</em>`:''}${controls}`;
}
function studioShell(title,subtitle,content){
  const top=studioHeader(title,`${subtitle} ${dataBadge()}`,title==='Dashboard'?synthButton():'');
  if(modelState.loading){
    if(title==='Dashboard' && modelState.data)return top+content();
    return top+'<section class="dash-card studio-message" role="status"><span class="studio-spinner"></span><h2>Loading model predictions</h2><p>Connecting to GridToEv and calculating charging scenarios.</p></section>';
  }
  if(modelState.error)return top+`<section class="dash-card studio-message" role="alert"><h2>Forecast unavailable</h2><p>${escapeHtml(modelState.error)}</p><button class="studio-button" id="model-retry" type="button">Try again ${icon('arrow',17)}</button></section>`;
  return top+content();
}
function cardHead(tone,title,subtitle,extra=''){return `<div class="dash-card-head"><span class="dash-accent is-${tone}" aria-hidden="true"></span><div class="dash-head-copy"><h2>${title}</h2><p>${subtitle}</p></div>${extra}</div>`}
function metric(label,value,unit='',note='',tone=''){return `<div class="studio-metric ${tone}"><span>${label}</span><strong>${value}<small>${unit}</small></strong><em>${note}</em></div>`}
function statStrip(items){return `<section class="studio-stat-strip" aria-label="Selected forecast metrics">${items.join('')}</section>`}
function provenance(){const d=modelState.data,zone=settings.timezone==='Europe/Dublin'?'Irish time':escapeHtml(settings.timezone),issued=d.predictions.map(p=>`+${p.horizonMinutes} min issued ${escapeHtml(modelTime(p.issuedAt))}`).join(', ');return `<p class="studio-provenance">${isDemoData()?`Offline example (simulated) while the forecast model is unavailable · not a real forecast for any half-hour`:`<b>Historical dataset prediction, not a live forecast</b> · GridToEv V1 · target ${escapeHtml(modelTime(d.predictions[0].targetAt,true))} ${zone} (${issued})${d.stale?' · last real result, model unreachable':''} · ${escapeHtml(d.selection?.note||'')}`} · Both horizons forecast the same half-hour · ${RECOVERY_CAVEAT}</p>`}
function renderCharging(){return studioShell('Charging','Shape a flexible-load scenario around the model forecast.',(()=>{const p=selectedPrediction(),o=scenarioOutcome(p),s=modelState.data.scenario;return `${statStrip([metric('Total demand',n(s.totalDemandMwh),'MWh','Scenario input'),metric('Flexible demand',n(s.flexibleDemandMwh),'MWh','Available at either target','green'),metric('Potential absorption',n(o.potentialRecoveryMwh),'MWh','Selected target'),metric('Proposed power',n(o.proposedPowerMw),'MW',o.powerLimitRespected?'Within capacity':'Above capacity','amber')])}<div class="studio-page-grid"><section class="dash-card studio-chart-card">${cardHead('orange','Charging opportunity','Separate +30 and +60 minute alternatives')}${comparisonChart('charging')}</section><section class="dash-card studio-side-card">${cardHead('green','Charging assumptions','Edit demand used by all pages')}<form id="charging-scenario-form" class="studio-form"><label for="scenario-total">Total demand <span>kWh</span></label><input id="scenario-total" type="number" min="0" max="1000000000" step="any" required value="${modelState.totalDemandKwh}"><label for="scenario-flexible">Flexible demand <span>kWh</span></label><input id="scenario-flexible" type="number" min="0" max="1000000000" step="any" required value="${modelState.flexibleDemandKwh}"><p id="scenario-validation" role="alert"></p><button class="studio-button" type="submit">Apply scenario ${icon('arrow',17)}</button></form><div class="studio-side-number"><span>Remaining demand</span><strong>${n(o.remainingDemandMwh)} MWh</strong><small>Must be scheduled separately</small></div><p class="studio-note">This estimates possible absorption. Vehicle counts, deadlines and charging schedules are not supplied by the model.</p></section></div>${provenance()}`}))}
function settingSwitch(label,key,description){const active=key==='theme'?dashboardTheme==='dark':settings[key];const action=key==='theme'?'data-dashboard-theme':`data-toggle="${key}"`;return `<div class="studio-setting"><div><strong>${label}</strong><span>${description}</span></div><button type="button" class="studio-switch ${active?'active':''}" ${action} role="switch" aria-checked="${active}" aria-label="${label}"><i></i></button></div>`}
