function n(value){return modelNumber(value)}
function pct(value){return value===null?'—':`${n(value*100)}%`}
function studioHeader(title,subtitle,actions=''){const art={Forecast:'forecast',Charging:'charging',Impact:'impact',Settings:'settings'}[title]||'overview';return `<header class="dash-header studio-header"><div class="dashboard-header-art is-${art}" aria-hidden="true"></div><div class="dash-title"><p>Renewable energy planner / Ireland</p><h1>${title}</h1><span>${subtitle}</span></div>${actions}</header>`}
// The shared forecast is a GridToEv V1 historical dataset prediction (latest target in the
// dataset), never a live forecast, so every page that shows it says so in its header.
function dataBadge(){const d=modelState.data;if(!d)return '';return isDemoData()?'<em class="data-badge is-demo">Simulated demo data</em>':`<em class="data-badge">Historical dataset prediction · target ${escapeHtml(modelTime(d.predictions[0].targetAt,true))} · not a live forecast</em>`}
function studioShell(title,subtitle,content){
  const top=studioHeader(title,`${subtitle} ${dataBadge()}`,title==='Dashboard'?synthButton():'');
  if(modelState.loading){
    if(title==='Dashboard' && modelState.data)return top+content();
    return top+'<section class="dash-card studio-message" role="status"><span class="studio-spinner"></span><h2>Loading model predictions</h2><p>Connecting to GridToEv and calculating charging scenarios.</p></section>';
  }
  if(modelState.error)return top+`<section class="dash-card studio-message" role="alert"><h2>Forecast unavailable</h2><p>${escapeHtml(modelState.error)}</p><button class="studio-button" id="model-retry" type="button">Try again ${icon('arrow',17)}</button></section>`;
  return top+content();
}
function cardHead(tone,title,subtitle,extra=''){return `<div class="dash-card-head"><span class="dash-accent is-${tone}" aria-hidden="true"></span><div class="dash-head-copy"><h2>${title}</h2><p>${subtitle}</p></div>${extra}</div>`}
function metric(label,value,unit='',note='',tone=''){return `<div class="studio-metric ${tone}"><span>${label}</span><strong>${value}<small>${unit}</small></strong><em>${note}</em></div>`}
function statStrip(items){return `<section class="studio-stat-strip" aria-label="Selected forecast metrics">${items.join('')}</section>`}
function provenance(){const d=modelState.data,zone=settings.timezone==='Europe/Dublin'?'Irish time':escapeHtml(settings.timezone),issued=d.predictions.map(p=>`+${p.horizonMinutes} min issued ${escapeHtml(modelTime(p.issuedAt))}`).join(', ');return `<p class="studio-provenance">${isDemoData()?`Demo data while the forecast model is offline · Target ${escapeHtml(modelTime(d.predictions[0].targetAt))} ${zone}`:`<b>Historical dataset prediction, not a live forecast</b> · GridToEv V1 · target ${escapeHtml(modelTime(d.predictions[0].targetAt,true))} ${zone} (${issued})`} · Both horizons forecast the same half-hour · Recovery figures are estimates, not measured charging.</p>`}
function renderCharging(){return studioShell('Charging','Shape a flexible-load scenario around the model forecast.',(()=>{const p=selectedPrediction(),o=scenarioOutcome(p),s=modelState.data.scenario;return `${statStrip([metric('Total demand',n(s.totalDemandMwh),'MWh','Scenario input'),metric('Flexible demand',n(s.flexibleDemandMwh),'MWh','Available at either target','green'),metric('Potential absorption',n(o.potentialRecoveryMwh),'MWh','Selected target'),metric('Proposed power',n(o.proposedPowerMw),'MW',o.powerLimitRespected?'Within capacity':'Above capacity','amber')])}<div class="studio-page-grid"><section class="dash-card studio-chart-card">${cardHead('orange','Charging opportunity','Separate +30 and +60 minute alternatives')}${comparisonChart('charging')}</section><section class="dash-card studio-side-card">${cardHead('green','Charging assumptions','Edit demand used by all pages')}<form id="charging-scenario-form" class="studio-form"><label for="scenario-total">Total demand <span>kWh</span></label><input id="scenario-total" type="number" min="0" max="1000000000" step="any" required value="${modelState.totalDemandKwh}"><label for="scenario-flexible">Flexible demand <span>kWh</span></label><input id="scenario-flexible" type="number" min="0" max="1000000000" step="any" required value="${modelState.flexibleDemandKwh}"><p id="scenario-validation" role="alert"></p><button class="studio-button" type="submit">Apply scenario ${icon('arrow',17)}</button></form><div class="studio-side-number"><span>Remaining demand</span><strong>${n(o.remainingDemandMwh)} MWh</strong><small>Must be scheduled separately</small></div><p class="studio-note">This estimates possible absorption. Vehicle counts, deadlines and charging schedules are not supplied by the model.</p></section></div>${provenance()}`}))}
function renderImpact(){return studioShell('Impact','See the projected energy benefit of flexible charging.',(()=>{const p=selectedPrediction(),o=scenarioOutcome(p);return `${statStrip([metric('At-risk energy',n(o.atRiskMwh),'MWh','Model prediction','amber'),metric('Potential recovery',n(o.potentialRecoveryMwh),'MWh','Scenario estimate','green'),metric('Remaining at risk',n(o.remainingWasteMwh),'MWh','After potential absorption'),metric('Recovery rate',pct(o.recoveryRate),'','Selected half-hour')])}<div class="studio-page-grid"><section class="dash-card studio-chart-card">${cardHead('green','Potential recovery by target','Two alternatives evaluated with the same demand')}${comparisonChart('impact')}</section><section class="dash-card studio-side-card">${cardHead('green','Energy balance','Selected forecast target')}${dashboardRecoveryChannel(p,o)}<div class="studio-balance"><div><i class="is-green"></i><span>Could be absorbed</span><strong>${n(o.potentialRecoveryMwh)} MWh</strong></div><div><i class="is-amber"></i><span>May remain at risk</span><strong>${n(o.remainingWasteMwh)} MWh</strong></div></div><p class="studio-note">Projected from a historical model forecast and user-entered demand. No actual charging, emissions or financial savings are measured.</p><button class="studio-button" data-page="charging" type="button">Adjust charging scenario ${icon('arrow',17)}</button></section></div>${provenance()}`}))}
function settingSwitch(label,key,description){const active=key==='theme'?dashboardTheme==='dark':settings[key];const action=key==='theme'?'data-dashboard-theme':`data-toggle="${key}"`;return `<div class="studio-setting"><div><strong>${label}</strong><span>${description}</span></div><button type="button" class="studio-switch ${active?'active':''}" ${action} role="switch" aria-checked="${active}" aria-label="${label}"><i></i></button></div>`}
